### ISSUE TITLE
Can we please have the npm package name react-schedule?

### ISSUE THREAD

**Issue by TylerAHolden** [Fi1osof/react_schedule#1]
NextGen Code Company is building an open source react schedule and schedular UI components and we would like to name it react-schedule. We saw that your project hasn't been updated in 2 years so it seems like you arent using it... Would you be willing to let us have the npm name?

**Comment by Fi1osof** [comment]
Sorry, I can’t do this, because this component is used in various projects. For a long time there were no updates because there were no complaints, but it fulfills its tasks.
You may name your component f.e. @nextgen/react-schedule
